name: Terraform Secret Management (Local Backend)

on:
  push:
    branches:
      - main
      - dev

      - staging

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      SECRET_VALUE: ${{ secrets.SECRET_VALUE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0


      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="secret_value=${SECRET_VALUE}"

      - name: Terraform Apply
        run: terraform apply -var="secret_value=${SECRET_VALUE}" -auto-approve

      - name: List files (debug)
        run: ls -la

      - name: Upload deployment log
        uses: actions/upload-artifact@v4
        with:
          name: deployment-log
          path: ./deployment.log
